/* Generated by re2c 3.0 on Thu Aug 25 13:25:13 2022 */
#line 1 "lexer.l"
#include <stdio.h>

const char *lex(const char *s)
{
    
#line 9 "<stdout>"
{
	char yych;
	yych = *s;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy2;
		default: goto yy1;
	}
yy1:
	++s;
#line 11 "lexer.l"
	{ return "TOK_ANY"; }
#line 30 "<stdout>"
yy2:
	yych = *++s;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy2;
		default: goto yy3;
	}
yy3:
#line 10 "lexer.l"
	{ return "TOK_NUMBER"; }
#line 49 "<stdout>"
}
#line 12 "lexer.l"


    return "";
}

int main(int argc, char *argv[])
{
    printf("%s\n", lex(argv[1]));

    return 0;
}
