FROM debian:bullseye-slim

ENV BISON_VERSION v3.8.2
ENV AUTOCONF_VERSION 2.71

RUN set -eux; \
    apt-get update; \
    apt-get install -y \
        automake \
        autopoint \
        ca-certificates \
        flex \
        gettext \
        gcc \
        git \
        gperf \
        graphviz \
        help2man \
        libc6-dev \
        m4 \
        make \
        texinfo \
        wget \
        xsltproc

RUN set -eux; \
	wget ftp://ftp.gnu.org/gnu/autoconf/autoconf-$AUTOCONF_VERSION.tar.gz; \
	tar -xvzf autoconf-$AUTOCONF_VERSION.tar.gz; \
    cd /autoconf-$AUTOCONF_VERSION; \
	./configure; \
	make; \
	make install

RUN set -eux; \
	git clone --branch=$BISON_VERSION --depth=1 https://github.com/akimd/bison.git /bison; \
	cd /bison; \
	git submodule update --init --recursive; \
	./bootstrap; \
	./configure; \
	make; \
	make install
