FROM php:7.4-cli-buster

# RUN pecl install ast
# RUN echo "zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20210902/ast.so" > /usr/local/lib/php.ini
# RUN echo "extension=ast.so" > /usr/local/etc/php/php.ini
